version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev # or Dockerfile.prod
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: gymdb
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: gymdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
